version: '3.6'

services:
    mysql:
        image: mysql:8.0 # intel only
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=mysqalx
            - MYSQL_USER=mysqalx
            - MYSQL_PASSWORD=mysqalx
            - MYSQL_DATABASE=mysqalx
